const data = [
  {
    id: 1,
    date: "1/05/2024",
    day: "Wednesday",
    enFestivalName: "International Workers' Day",
    enDescription: "fixed day in Gregorian calendar",
    hiFestivalName: "अंतर्राष्ट्रीय श्रमिक दिवस",
    hiDescription: "ग्रेगोरियन कैलेंडर में निश्चित दिन",
    saFestivalName: "",
    saDescription: "",
  },
  {
    id: 2,
    date: "1/05/2024",
    day: "Wednesday",
    enFestivalName: "Kalashtami",
    enDescription: "Vaishakha, Krishna Ashtami",
    hiFestivalName: "कालाष्टमी",
    hiDescription: "वैशाख, कृष्ण अष्टम",
    saFestivalName: "",
    saDescription: "",
  },

  {
    id: 3,
    date: "1/05/2024",
    day: "Wednesday",
    enFestivalName: "Masik Krishna Janmashtami",
    enDescription: "Vaishakha, Krishna Ashtami",
    hiFestivalName: "मासिक कृष्ण जन्माष्टमी",
    hiDescription: "वैशाख, कृष्ण अष्टमी",
    saFestivalName: "",
    saDescription: "",
  },

  {
    id: 4,
    date: "4/05/2024",
    day: "Saturday",
    enFestivalName: "Vallabhacharya Jayanti",
    enDescription: "Vaishakha, Krishna Ekadashi",
    hiFestivalName: "वल्लभाचार्य जयंती",
    hiDescription: "वैशाख, कृष्ण एकादशी",
    saFestivalName: "",
    saDescription: "",
  },

  {
    id: 5,
    date: "4/05/2024",
    day: "Saturday",
    enFestivalName: "Agni Nakshatram Begins",
    enDescription: "based on Solar calendar",
    hiFestivalName: "अग्नि नक्षत्रम् प्रारम्भ",
    hiDescription: "सौर कैलेंडर पर आधारित",
    saFestivalName: "",
    saDescription: "",
  },

  {
    id: 6,
    date: "4/05/2024",
    day: "Saturday",
    enFestivalName: "Varuthini Ekadashi",
    enDescription: "Vaishakha, Krishna Ekadashi",
    hiFestivalName: "वरुथिनी एकादशी",
    hiDescription: "वैशाख, कृष्ण एकादशी",
    saFestivalName: "",
    saDescription: "",
  },

  {
    id: 7,
    date: "5/05/2024",
    day: "Sunday",
    enFestivalName: "World Laughter Day",
    enDescription: "1st Sunday of May",
    hiFestivalName: "विश्व हँसी दिवस",
    hiDescription: "मई का पहला रविवार",
    saFestivalName: "",
    saDescription: "",
  },

  {
    id: 8,
    date: "5/05/2024",
    day: "Sunday",
    enFestivalName: "Pradosh Vrat",
    enDescription: "Vaishakha, Krishna Trayodashi",
    hiFestivalName: "प्रदोष व्रत",
    hiDescription: "वैशाख, कृष्ण त्रयोदशी",
    saFestivalName: "",
    saDescription: "",
  },

  {
    id: 9,
    date: "6/05/2024",
    day: "Monday",
    enFestivalName: "Masik Shivaratri",
    enDescription: "Vaishakha, Krishna Chaturdashi",
    hiFestivalName: "मासिक शिवरात्रि",
    hiDescription: "वैशाख, कृष्ण चतुर्दशी",
    saFestivalName: "",
    saDescription: "",
  },

  {
    id: 10,
    date: "7/05/2024",
    day: "Tuesday",
    enFestivalName: "Rabindranath Tagore Jayanti",
    enDescription: "fixed day in Gregorian calendar",
    hiFestivalName: "रवीन्द्रनाथ टैगोर जयंती",
    hiDescription: "ग्रेगोरियन कैलेंडर में निश्चित दिन",
    saFestivalName: "",
    saDescription: "",
  },

  {
    id: 11,
    date: "7/05/2024",
    day: "Tuesday",
    enFestivalName: "Darsha Amavasya",
    enDescription: "Vaishakha, Krishna Amavasya",
    hiFestivalName: "दर्श अमावस्या",
    hiDescription: "वैशाख, कृष्ण अमावस्या",
    saFestivalName: "",
    saDescription: "",
  },

  {
    id: 12,
    date: "7/05/2024",
    day: "Tuesday",
    enFestivalName: "Anvadhan",
    enDescription: "Vaishakha, Krishna Chaturdashi",
    hiFestivalName: "अनवधान",
    hiDescription: "वैशाख, कृष्ण चतुर्दशी",
    saFestivalName: "",
    saDescription: "",
  },

  {
    id: 13,
    date: "8/05/2024",
    day: "Wednesday",
    enFestivalName: "Tagore Jayanti *Bengal",
    enDescription: "based on Bengali calendar",
    hiFestivalName: "टैगोर जयंती *बंगाल",
    hiDescription: "बंगाली कैलेंडर पर आधारित",
    saFestivalName: "",
    saDescription: "",
  },

  {
    id: 14,
    date: "8/05/2024",
    day: "Wednesday",
    enFestivalName: "Masik Karthigai",
    enDescription: "based on Solar calendar",
    hiFestivalName: "मासिक कार्तिगाई",
    hiDescription: "सौर कैलेंडर पर आधारित",
    saFestivalName: "",
    saDescription: "",
  },

  {
    id: 15,
    date: "8/05/2024",
    day: "Wednesday",
    enFestivalName: "Ishti",
    enDescription: "Vaishakha, Krishna Amavasya",
    hiFestivalName: "इश्ति",
    hiDescription: "वैशाख, कृष्ण अमावस्या",
    saFestivalName: "",
    saDescription: "",
  },
];
export default data;
